services:
  db:
    build: ./database
    container_name: nfl_postgres
    environment:
      POSTGRES_DB: nfldb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  flyway:
    image: flyway/flyway
    command: -configFiles=/flyway/conf/flyway.conf migrate
    volumes:
      - ./database/migrations:/flyway/sql
      - ./database/flyway.conf:/flyway/conf/flyway.conf
    depends_on:
      db:
        condition: service_healthy

  backend:
    build: ./backend
    container_name: nfl_backend
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/nfldb
      NODE_ENV: development
    ports:
      - "8080:8080"
    depends_on:
      - flyway
    volumes:
      - ./backend:/app
      - /app/node_modules
volumes:
  postgres_data: